### ISSUE TITLE
documentation link offline

### ISSUE THREAD

**Issue by andreasthoelke** [AvisoNovate/rook#38]
The documentation link 
https://portal.aviso.io/#/docs/open-source
seems to be offline.

**Comment by hlship** [comment]
Pretty sure it's back up now!

We're still working on the documentation aspect; we have an in-house system to generate the documentation and, as you can see, it exposes multiple versions (we can fine tune exactly which ones even, which will be more useful when we get to a 1.0).

However, it's not always stable, and I'm dependent on someone inside Aviso for some maintenance issues.
