### ISSUE TITLE
Memoize dependency 

### ISSUE THREAD

**Issue by mhuebert** [AvisoNovate/rook#40]
After adding rook to my project, I see this error:

```
clojure.lang.ExceptionInfo: No such var: clojure.core.cache/through
    data: {:file "clojure/core/memoize.clj", :line 64}
```

~~It was fixed by adding `[org.clojure/core.memoize "0.5.6"]` to my dependencies (which I found [here](https://groups.google.com/forum/#!msg/light-table-discussion/f4kpZLFGBV8/oyFPaJ4yvwwJ)).~~ I spoke too soon - I'm still getting the error. Will update this if I figure it out.

I am relatively new to Clojure and boot and don't know what the problem is. I am guessing it's caused by a dependency conflict and is likely not a problem with rook, but I thought I'd post this here in case others see the same thing.

Full boot file: https://gist.github.com/mhuebert/5ad0a8d36455103aea78

**Comment by mhuebert** [comment]
The conflict seems to be with [com.cemerick/friend "0.2.1"]. If I comment out that dependency, I don't see this error.

**Comment by mhuebert** [comment]
`lein deps :tree` offers the following warning/suggestion:

```clj
[com.cemerick/friend "0.2.1"] -> [org.clojure/core.cache "0.6.2"]
 overrides
[io.aviso/rook "0.1.27"] -> [ring-middleware-format "0.5.0" :exclusions [ring/ring-devel org.clojure/tools.reader ring]] -> [org.clojure/core.memoize "0.5.7"] -> [org.clojure/core.cache "0.6.4"]

Consider using these exclusions:
[io.aviso/rook "0.1.27" :exclusions [org.clojure/core.cache]]
```

This does not work. However, if we exclude core.cache from friend, the project runs:

```clj
[com.cemerick/friend "0.2.1" :exclusions [org.clojure/core.cache]]
```

I don't know if this will cause unintended behavior with `friend`.

**Comment by hlship** [comment]
Please provide a minimal example project that demonstrates this problem, and reopen this issue. I don't believe it is in Rook.
